name: Release X-UI

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [amd64]
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.6.0

      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.21'

      - name: Get dependencies
        run: |
          go get github.com/shirou/gopsutil/v3/cpu
          go get github.com/shirou/gopsutil/v3/disk
          go get github.com/shirou/gopsutil/v3/host
          go get github.com/shirou/gopsutil/v3/load
          go get github.com/shirou/gopsutil/v3/mem
          go get github.com/shirou/gopsutil/v3/net

      - name: Build
        run: |
          export CGO_ENABLED=1
          export GOOS=windows
          export GOARCH=${{ matrix.platform }}
          go build -o xui-release.exe -v main.go

          mkdir x-ui
          cp xui-release.exe x-ui/
          cp x-ui.service x-ui/
          cp x-ui.sh x-ui/
          mv x-ui/xui-release.exe x-ui/x-ui.exe
          mkdir x-ui/bin
          cd x-ui/bin

          # Download dependencies
          if [ "${{ matrix.platform }}" == "amd64" ]; then
            wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-windows-64.zip
            unzip Xray-windows-64.zip
            rm -f Xray-windows-64.zip
          fi

          rm -f geoip.dat geosite.dat iran.dat  
          
          wget https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat  
          
          wget https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat  
          
          wget https://github.com/MasterKia/iran-hosted-domains/releases/latest/download/iran.dat  
          
          mv xray xray-windows-${{ matrix.platform }}.exe  
          
          cd ../..

      - name: Package  
        run: tar -zcvf x-ui-windows-${{ matrix.platform }}.tar.gz x-ui  

      - name: Upload  
        uses: svenstaro/upload-release-action@2.7.0  
        with:  
          repo_token: ${{ secrets.GITHUB_TOKEN }}  
          
          tag: ${{ github.ref }}  
          
          file: x-ui-windows-${{ matrix.platform }}.tar.gz  
          
          asset_name: x-ui-windows-${{ matrix.platform }}.tar.gz  
          
          prerelease: true  
          
          overwrite: true
